export const industries = [
  "Art & Entertainment",
  "Automotive",
  "Blogging & Social Media",
  "Business",
  "Computer",
  "Design",
  "Education",
  "Environment",
  "Events / Trade Shows",
  "Games & Entertainment",
  "Government",
  "Health and Fitness",
  "Home & Family",
  "Industry",
  "Legal / Law",
  "Lifestyle",
  "News & Society",
  "Politics",
  "Religion",
  "Sports",
  "Technology",
  "Web sites / Internet",
];
